### ISSUE TITLE
Add method to trigger Kebechet internally

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/common#1009]
Currently we have a method to trigger kebechet externally with a webhook, we need a internal trigger method that would allow us to run kebechet without a webhook

- [x] Add a argo-worflow with subcommand set to `run-url` and doesn't takes in the following env variables - `KEBECHET_REPO_URL` and `KEBECHET_SERVICE_NAME`

- [x] Add a method in thoth-common to use `run-url` subcommand and run kebechet on the repo.

**Comment by fridex** [comment]
Would it make sense to reuse the `run-url` command here and keep kebechet logic untouched? I think a component that will trigger kebechet (for internal trigger use case) will be responsible for filling in the environment variables (options).

**Comment by fridex** [comment]
> We would need a new method in common, right? and the env variables like repo url as a parameter or is there a better way?

A component that would be run prior to Kebechet, it would query the database for all the repositories for which the update should be propagated. For these computed repositories, it would compute corresponding `KEBECHET_REPO_URL` and `KEBECHET_SERVICE_NAME` for kebechet jobs triggered as subsequent tasks in the internal trigger workflow.

**Comment by saisankargochhayat** [comment]
Yes, that is what we discussed the other day, this issue made as we would anyway need a method called `Openshift.schedule_kebechet_run_url(repo, gitservice_repo_name)` as used [here](https://github.com/thoth-station/investigator/pull/313/files#diff-478a6e397a238cbc816dfc40bbfc1c3bR55) and a new corresponding template. Which would also be called by the new component as you have mentioned above.

**Comment by pacospace** [comment]
> Yes, that is what we discussed the other day, this issue was made as we would anyway need a method called `Openshift.schedule_kebechet_run_url(repo, gitservice_repo_name)` as used [here](https://github.com/thoth-station/investigator/pull/313/files#diff-478a6e397a238cbc816dfc40bbfc1c3bR55) and a new corresponding template. Which would also be called by the new component as you have mentioned above. Am I missing something?

Yes that method would be the actual Kebechet trigger and if for example:

- MissingPackageVersion is sent as message by package_update we will trigger a new workflow (KebechetAdministrator or KebechetSupervisor?) that does what discussed and then at the end send many messages to trigger many Kebechet workflows using `Openshift.schedule_kebechet_run_url(repo, gitservice_repo_name)`

**Comment by pacospace** [comment]
> > Yes, that is what we discussed the other day, this issue was made as we would anyway need a method called `Openshift.schedule_kebechet_run_url(repo, gitservice_repo_name)` as used [here](https://github.com/thoth-station/investigator/pull/313/files#diff-478a6e397a238cbc816dfc40bbfc1c3bR55) and a new corresponding template. Which would also be called by the new component as you have mentioned above. Am I missing something?
> 
> Yes that method would be the actual Kebechet trigger and if for example:
> 
> * MissingPackageVersion is sent as message by package_update we will trigger a new workflow (KebechetAdministrator or KebechetSupervisor?) that does what discussed and then at the end send many messages to trigger many Kebechet workflows using `Openshift.schedule_kebechet_run_url(repo, gitservice_repo_name)`

We actually need to create two new messages:

- KebechetAdministratorTrigger

- KebechetRunURLTrigger, KebechetTrigger would remain for the one from webhook or we could rename it to KebechetWebhookTrigger or we call the internal one with a new name :D

**Comment by fridex** [comment]
Can we create a docs for these messages and create a naming convention?

**Comment by pacospace** [comment]
> Can we create a docs for these messages and create a naming convention?

Should we include them all in: https://github.com/thoth-station/investigator/issues/287

**Comment by pacospace** [comment]
@saisankargochhayat can we close this?

**Comment by saisankargochhayat** [comment]
Yes solved along with - https://github.com/thoth-station/workflow-helpers/issues/148
