### ISSUE TITLE
error: Module 'sentry_sdk' has no attribute 'init'  [attr-defined]

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/common#1031]
**Describe the bug**
When you run `pre-commit` check locally, you see below error:
```
thoth/common/logging.py:33:1: error: Module 'sentry_sdk' has no attribute 'init'  [attr-defined]
Found 1 error in 1 file (checked 13 source files)
```
But, the interesting thing is that on the `ci run`, you don't see that error.

**To Reproduce**
1. Clone this repo
2. Run `pre-commit run --all-files`
3. See error

**Expected behavior**
It should pass all pre-commit tests locally and on the ci-run

**Comment by fridex** [comment]
@bissenbay do you want to work on this one?

**Comment by goern** [comment]
@fridex is this still valid?

**Comment by fridex** [comment]
pre-commit checks pass, closing.

/close
