### ISSUE TITLE
Does this repo need `.aicoe-ci.yaml`?

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/common#1051]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshad16** [comment]
please follow this comment: https://github.com/thoth-station/analyzer/issues/292#issuecomment-736007922

**Comment by bissenbay** [comment]
> please follow this comment: [thoth-station/analyzer#292 (comment)](https://github.com/thoth-station/analyzer/issues/292#issuecomment-736007922)

thanks

**Comment by fridex** [comment]
Already present in the repo. Closing and thanks! :+1:
