### ISSUE TITLE
WIP: use operate-first Loki for logging

### ISSUE THREAD

**Issue by goern** [thoth-station/common#1089]
**Is your feature request related to a problem? Please describe.**
Now that Loki is available from Operate First https://github.com/operate-first/apps/tree/master/docs/observatorium/loki we should use it for out logging backend. 

Let's use one loki org-id per tooth deployment-name

**Describe the solution you'd like**
common logging should configure and use loki in a way that is transparent to all the dependant components.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**References**
https://pypi.org/project/python-logging-loki/

/kind feature
/assign @fridex 
/lable sig/devops

**Comment by fridex** [comment]
/close

This will probably not lend in thoth-common implementation. Closing, we can revisit this based on op1st.
