### ISSUE TITLE
How to check that workflow has finished?

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/common#1139]
**Is your feature request related to a problem? Please describe.**
What's the current logic of waiting for workflows being finished? Should it be just regular polling (i.e. refreshing the status of `get_workflow_status_report()` in loop) or a wait method is available (something that would be semantically similar to `wait_until_finished( workflow_id )`) ?

Reason why I am asking:
The kebechet analysis data aggregation done by `mi-scheduler` using `mi` (see https://github.com/thoth-station/mi-scheduler/issues/99) needs to know, when are all the analysis workflows finished, so that the last step in `mi-scheduler` pipeline can be done, and that is the data merge of all gathered files. In order for that to work, I have to know when all the workflows are finished.

**Comment by xtuchyna** [comment]
This was resolved on scrum and it was said that it can be closed. However, maybe this would be a good QnA in the documentation? wdyt?

**Comment by goern** [comment]
@xtuchyna please go ahead... is this a general Workflow question or a Thoth developer question? Where shall we put the answer?

/sig docs
/remove-kind feature

**Comment by xtuchyna** [comment]
I think that this is more of a thoth developer question from the `thoth.common` point of view, rather than general workflow quesiton (I think that argo has option `wait` that waits until workflow is finished).

Don't know where the answer should be, maybe a new README [here](https://github.com/thoth-station/common/tree/master/thoth/common) ?

**Comment by fridex** [comment]
I'm not sure if this should go to docs. This is an architectural question and the async solution is a general pattern we established in the application.

**Comment by xtuchyna** [comment]
therefore, this can be closed :+1:
