### ISSUE TITLE
Migrate to pyproject.toml

### ISSUE THREAD

**Issue by VannTen** [thoth-station/common#1287]
Translate setup.py into a pyproject.toml file  

/kind feature
/triage accepted
/sig stack-guidance
/good-first-issue
/label hacktoberfest

Parent issue: https://github.com/thoth-station/core/issues/360

**Comment by ChandanChainani** [comment]
Hi @sesheta can i work on the issue?

**Comment by theyashl** [comment]
Hi @VannTen , I have raised the MR with required changes, can you please have a look and let me know if any changes are required?

**Comment by ChandanChainani** [comment]
@harshad16 since the pr is merged please can you close the issue

**Comment by harshad16** [comment]
Thank you @theyashl and @ChandanChainani  for the PR 
and for the contributions.
awesome work :100:
