### ISSUE TITLE
Change formatting of logged messages to have datetime in UTC

### ISSUE THREAD

**Issue by fridex** [thoth-station/common#487]
**Describe the bug**

As our team is spread all over the world, it would be a good idea to produce logs which are not dependent on timezone or explicitly state timezone in the logs.

**Expected behavior**

The formatted logger string should be timezone-aware or be in UTC:

https://github.com/thoth-station/common/blob/57a14cacfbccf36db949fee3b445ad114359a3c7/thoth/common/logging.py#L93

**Comment by goern** [comment]
erm... TZ should always be UTC, shouldnt it?

**Comment by fridex** [comment]
> erm... TZ should always be UTC, shouldnt it?

+1 for UTC
