### ISSUE TITLE
do not assign IMAGE_STREAM_NAMESPACE parameter to template

### ISSUE THREAD

**Issue by goern** [thoth-station/common#886]
**Is your feature request related to a problem? Please describe.**
user-api logs `2020-06-25 18:38:06,785  25 WARNING  thoth.common.openshift:315: Requested to assign parameter 'IMAGE_STREAM_NAMESPACE' (value 'thoth-test-core') to template but template does not provide the given parameter, forcing...`

this could be avoided by changing how we process the template

**Describe the solution you'd like**
stop assigning the parameter during template processing

**Comment by fridex** [comment]
I think this one is no longer relevant. We do not assign image stream namespace anymore.
